name: vault
description: Offline and Online Vault Application

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  intl: ^0.17.0
  file_picker: ^5.5.0
  path_provider: ^2.0.5
  url_launcher: ^6.0.9
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3

  cupertino_icons: ^1.0.2
  firebase_storage: ^11.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
